INSERT INTO Airport (nom, code) VALUES ('Djerba, Tunisia ', 'DJE');
INSERT INTO Airport (nom, code) VALUES ('Gafsa, Tunisia ', 'GAF');
INSERT INTO Airport (nom, code) VALUES ('Monastir, Tunisia ', 'MIR');
INSERT INTO Airport (nom, code) VALUES ('Tabarka, Tunisia ', 'TBJ');
INSERT INTO Airport (nom, code) VALUES ('Tozeur, Tunisia ', 'TOE');
INSERT INTO Airport (nom, code) VALUES ('Tunis, Tunisia ', 'TUN');
INSERT INTO Airport (nom, code) VALUES ('Hurghada, Egypt ', 'HRG');
INSERT INTO Airport (nom, code) VALUES ('Kharga, Egypt ', 'UVL');
INSERT INTO Airport (nom, code) VALUES ('Luxor, Egypt ', 'LXR');
INSERT INTO Airport (nom, code) VALUES ('Mersa Matruh, Egypt ', 'MUH');
INSERT INTO Airport (nom, code) VALUES ('Sharm El Sheikh, Egypt ', 'SSH');
INSERT INTO Airport (nom, code) VALUES ('Taba, Egypt ', 'TCP');
INSERT INTO Airport (nom, code) VALUES ('Abu Simbel, Egypt ', 'ABS');
INSERT INTO Airport (nom, code) VALUES ('Al Arish, Egypt ', 'AAC');
INSERT INTO Airport (nom, code) VALUES ('Alexandria, Egypt ', 'ALY');
INSERT INTO Airport (nom, code) VALUES ('Assiut, Egypt ', 'ATZ');
INSERT INTO Airport (nom, code) VALUES ('Aswan, Egypt ', 'ASW');
INSERT INTO Airport (nom, code) VALUES ('Borg El Arab, Egypt ', 'HBE');
INSERT INTO Airport (nom, code) VALUES ('Cairo, Egypt ', 'CAI');
INSERT INTO Airport (nom, code) VALUES ('Adrar, Algeria ', 'AZR');
INSERT INTO Airport (nom, code) VALUES ('Algiers, Algeria ', 'ALG');
INSERT INTO Airport (nom, code) VALUES ('Annaba, Algeria ', 'AAE');
INSERT INTO Airport (nom, code) VALUES ('Batna, Algeria ', 'BLJ');
INSERT INTO Airport (nom, code) VALUES ('Bechar, Algeria ', 'CBH');
INSERT INTO Airport (nom, code) VALUES ('Bejaia, Algeria ', 'BJA');
INSERT INTO Airport (nom, code) VALUES ('Biskra, Algeria ', 'BSK');
INSERT INTO Airport (nom, code) VALUES ('Constantine, Algeria ', 'CZL');
INSERT INTO Airport (nom, code) VALUES ('Djanet, Algeria ', 'DJG');
INSERT INTO Airport (nom, code) VALUES ('Ghardala, Algeria ', 'GHA');
INSERT INTO Airport (nom, code) VALUES ('El Oved, Algeria ', 'ELU');
INSERT INTO Airport (nom, code) VALUES ('Oran, Algeria ', 'ORN');
INSERT INTO Airport (nom, code) VALUES ('Tbessa, Algeria ', 'TEE');

INSERT INTO Town VALUES (1,'Tunis','Tunisia','Marsa');
INSERT INTO Town VALUES (2,'Tunis','Tunisia','M. Ville');
INSERT INTO Town VALUES (3,'Tunis','Tunisia','Bab Souiqa');
INSERT INTO Town VALUES (4,'Tunis','Tunisia','Gammarth');
INSERT INTO Town VALUES (5,'Tunis','Tunisia','La Goulette');
INSERT INTO Town VALUES (6,'Tunis','Tunisia','Bardo');
INSERT INTO Town VALUES (7,'Ben Arous','Tunisia','Rades');
INSERT INTO Town VALUES (8,'Ben Arous','Tunisia','Ezzahra');
INSERT INTO Town VALUES (9,'Ben Arous','Tunisia','Hammam Lif');
INSERT INTO Town VALUES (10,'Ben Arous','Tunisia','Fouchena');
INSERT INTO Town VALUES (11,'Ben Arous','Tunisia','Mohammadia');
INSERT INTO Town VALUES (12,'Sfax','Tunisia','Seqyet Deyer');
INSERT INTO Town VALUES (13,'Sfax','Tunisia','Seqyet Zit');
INSERT INTO Town VALUES (14,'Sfax','Tunisia','Manzel Chaker');
INSERT INTO Town VALUES (15,'Sfax','Tunisia','Saltnia');
INSERT INTO Town VALUES (16,'Alger','Algeria','Agha');
INSERT INTO Town VALUES (17,'Alger','Algeria','El Harrach');
INSERT INTO Town VALUES (18,'Alger','Algeria','Matifou');
INSERT INTO Town VALUES (19,'Alger','Algeria','Argel');
INSERT INTO Town VALUES (20,'Oran','Algeria','Bel Caid');
INSERT INTO Town VALUES (21,'Oran','Algeria','Boisseville');
INSERT INTO Town VALUES (22,'Oran','Algeria','Damesme');
INSERT INTO Town VALUES (23,'Oran','Algeria','Douar Gotni');

INSERT INTO Direction VALUES (1,5,10,5,10,'TUN',1);
INSERT INTO Direction VALUES (2,5,10,5,10,'TUN',2);
INSERT INTO Direction VALUES (3,5,10,5,10,'TUN',3);
INSERT INTO Direction VALUES (4,5,10,5,10,'TUN',4);
INSERT INTO Direction VALUES (5,5,10,5,10,'TUN',5);
INSERT INTO Direction VALUES (6,5,10,5,10,'TUN',6);
INSERT INTO Direction VALUES (7,30,20,10,15,'TUN',7);
INSERT INTO Direction VALUES (8,30,20,10,15,'TUN',8);
INSERT INTO Direction VALUES (9,30,20,10,15,'TUN',9);
INSERT INTO Direction VALUES (10,30,20,10,15,'TUN',10);
INSERT INTO Direction VALUES (11,30,20,10,15,'TUN',11);
INSERT INTO Direction VALUES (12,200,50,10,25,'TUN',12);
INSERT INTO Direction VALUES (13,200,50,10,25,'TUN',13);
INSERT INTO Direction VALUES (14,200,50,10,25,'TUN',14);
INSERT INTO Direction VALUES (15,200,60,15,30,'DJE',12);
INSERT INTO Direction VALUES (16,200,60,15,30,'DJE',13);
INSERT INTO Direction VALUES (17,200,60,15,30,'DJE',14);
INSERT INTO Direction VALUES (18,200,60,15,30,'DJE',15);
INSERT INTO Direction VALUES (19,10,20,10,10,'ALG',16);
INSERT INTO Direction VALUES (20,10,20,10,10,'ALG',17);
INSERT INTO Direction VALUES (21,10,20,10,10,'ALG',18);
INSERT INTO Direction VALUES (22,10,20,10,10,'ALG',19);
commit;

